
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using nvc.localization;
	
			
namespace nvc.controls {
	public partial class SaveSettingsFormStrings: LocalizedStringsBase<SaveSettingsFormStrings>{
		


		private const string s_Title = @"Saving changes...";
		private string m_Title=null;
		[XPath(@"/localized-strings/module[@name='SaveSettingsFormStrings' and @namespace='nvc.controls']/descendant::string[@name='Title']/@value")]
		public string Title {
			get { 
				if( m_Title == null){
					return s_Title;
				}
				return m_Title; 
			}
			set { 
				if( value != m_Title){
					m_Title = value;
					NotifyPropertyChanged("Title");
				}
			}  
		}
	


		private const string s_Text = @"Please wait until changes will be applied";
		private string m_Text=null;
		[XPath(@"/localized-strings/module[@name='SaveSettingsFormStrings' and @namespace='nvc.controls']/descendant::string[@name='Text']/@value")]
		public string Text {
			get { 
				if( m_Text == null){
					return s_Text;
				}
				return m_Text; 
			}
			set { 
				if( value != m_Text){
					m_Text = value;
					NotifyPropertyChanged("Text");
				}
			}  
		}
	


		private const string s_NeedToReboot = @"Device need to be rebooted. Please refresh devices list.";
		private string m_NeedToReboot=null;
		[XPath(@"/localized-strings/module[@name='SaveSettingsFormStrings' and @namespace='nvc.controls']/descendant::string[@name='NeedToReboot']/@value")]
		public string NeedToReboot {
			get { 
				if( m_NeedToReboot == null){
					return s_NeedToReboot;
				}
				return m_NeedToReboot; 
			}
			set { 
				if( value != m_NeedToReboot){
					m_NeedToReboot = value;
					NotifyPropertyChanged("NeedToReboot");
				}
			}  
		}
	
	}

}
	
			
namespace nvc {
	public partial class Constants: LocalizedStringsBase<Constants>{
		


		private const string s_sExceptionWSDiscoveryTitle = @"WSDiscovery error";
		private string m_sExceptionWSDiscoveryTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sExceptionWSDiscoveryTitle']/@value")]
		public string sExceptionWSDiscoveryTitle {
			get { 
				if( m_sExceptionWSDiscoveryTitle == null){
					return s_sExceptionWSDiscoveryTitle;
				}
				return m_sExceptionWSDiscoveryTitle; 
			}
			set { 
				if( value != m_sExceptionWSDiscoveryTitle){
					m_sExceptionWSDiscoveryTitle = value;
					NotifyPropertyChanged("sExceptionWSDiscoveryTitle");
				}
			}  
		}
	


		private const string s_sErrorDevInfoNull = @"Error was during device configuration reading. Please refresh devices list";
		private string m_sErrorDevInfoNull=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorDevInfoNull']/@value")]
		public string sErrorDevInfoNull {
			get { 
				if( m_sErrorDevInfoNull == null){
					return s_sErrorDevInfoNull;
				}
				return m_sErrorDevInfoNull; 
			}
			set { 
				if( value != m_sErrorDevInfoNull){
					m_sErrorDevInfoNull = value;
					NotifyPropertyChanged("sErrorDevInfoNull");
				}
			}  
		}
	


		private const string s_sErrorDeviceName = @"none";
		private string m_sErrorDeviceName=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorDeviceName']/@value")]
		public string sErrorDeviceName {
			get { 
				if( m_sErrorDeviceName == null){
					return s_sErrorDeviceName;
				}
				return m_sErrorDeviceName; 
			}
			set { 
				if( value != m_sErrorDeviceName){
					m_sErrorDeviceName = value;
					NotifyPropertyChanged("sErrorDeviceName");
				}
			}  
		}
	


		private const string s_sErrorDeviceFirmware = @"none";
		private string m_sErrorDeviceFirmware=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorDeviceFirmware']/@value")]
		public string sErrorDeviceFirmware {
			get { 
				if( m_sErrorDeviceFirmware == null){
					return s_sErrorDeviceFirmware;
				}
				return m_sErrorDeviceFirmware; 
			}
			set { 
				if( value != m_sErrorDeviceFirmware){
					m_sErrorDeviceFirmware = value;
					NotifyPropertyChanged("sErrorDeviceFirmware");
				}
			}  
		}
	


		private const string s_sErrorSaveVideoStreaming = @"Error was during saving video streaming settings. Please refresh device.";
		private string m_sErrorSaveVideoStreaming=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorSaveVideoStreaming']/@value")]
		public string sErrorSaveVideoStreaming {
			get { 
				if( m_sErrorSaveVideoStreaming == null){
					return s_sErrorSaveVideoStreaming;
				}
				return m_sErrorSaveVideoStreaming; 
			}
			set { 
				if( value != m_sErrorSaveVideoStreaming){
					m_sErrorSaveVideoStreaming = value;
					NotifyPropertyChanged("sErrorSaveVideoStreaming");
				}
			}  
		}
	


		private const string s_sErrorSaveNetworkSettings = @"Error was during saving network settings. Please refresh device.";
		private string m_sErrorSaveNetworkSettings=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorSaveNetworkSettings']/@value")]
		public string sErrorSaveNetworkSettings {
			get { 
				if( m_sErrorSaveNetworkSettings == null){
					return s_sErrorSaveNetworkSettings;
				}
				return m_sErrorSaveNetworkSettings; 
			}
			set { 
				if( value != m_sErrorSaveNetworkSettings){
					m_sErrorSaveNetworkSettings = value;
					NotifyPropertyChanged("sErrorSaveNetworkSettings");
				}
			}  
		}
	


		private const string s_sErrorSaveDeviceNameSettings = @"Error was during saving device name. Please refresh device.";
		private string m_sErrorSaveDeviceNameSettings=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorSaveDeviceNameSettings']/@value")]
		public string sErrorSaveDeviceNameSettings {
			get { 
				if( m_sErrorSaveDeviceNameSettings == null){
					return s_sErrorSaveDeviceNameSettings;
				}
				return m_sErrorSaveDeviceNameSettings; 
			}
			set { 
				if( value != m_sErrorSaveDeviceNameSettings){
					m_sErrorSaveDeviceNameSettings = value;
					NotifyPropertyChanged("sErrorSaveDeviceNameSettings");
				}
			}  
		}
	


		private const string s_sErrorVlc = @"Media stream error";
		private string m_sErrorVlc=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorVlc']/@value")]
		public string sErrorVlc {
			get { 
				if( m_sErrorVlc == null){
					return s_sErrorVlc;
				}
				return m_sErrorVlc; 
			}
			set { 
				if( value != m_sErrorVlc){
					m_sErrorVlc = value;
					NotifyPropertyChanged("sErrorVlc");
				}
			}  
		}
	


		private const string s_sErrorVlcMediaUriIsEmpty = @"Stream uri is emtpy";
		private string m_sErrorVlcMediaUriIsEmpty=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorVlcMediaUriIsEmpty']/@value")]
		public string sErrorVlcMediaUriIsEmpty {
			get { 
				if( m_sErrorVlcMediaUriIsEmpty == null){
					return s_sErrorVlcMediaUriIsEmpty;
				}
				return m_sErrorVlcMediaUriIsEmpty; 
			}
			set { 
				if( value != m_sErrorVlcMediaUriIsEmpty){
					m_sErrorVlcMediaUriIsEmpty = value;
					NotifyPropertyChanged("sErrorVlcMediaUriIsEmpty");
				}
			}  
		}
	


		private const string s_sErrorVlcMediaUriIsBad = @"Stream uri is unknown";
		private string m_sErrorVlcMediaUriIsBad=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sErrorVlcMediaUriIsBad']/@value")]
		public string sErrorVlcMediaUriIsBad {
			get { 
				if( m_sErrorVlcMediaUriIsBad == null){
					return s_sErrorVlcMediaUriIsBad;
				}
				return m_sErrorVlcMediaUriIsBad; 
			}
			set { 
				if( value != m_sErrorVlcMediaUriIsBad){
					m_sErrorVlcMediaUriIsBad = value;
					NotifyPropertyChanged("sErrorVlcMediaUriIsBad");
				}
			}  
		}
	


		private const string s_sCommonAppOn = @"On";
		private string m_sCommonAppOn=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sCommonAppOn']/@value")]
		public string sCommonAppOn {
			get { 
				if( m_sCommonAppOn == null){
					return s_sCommonAppOn;
				}
				return m_sCommonAppOn; 
			}
			set { 
				if( value != m_sCommonAppOn){
					m_sCommonAppOn = value;
					NotifyPropertyChanged("sCommonAppOn");
				}
			}  
		}
	


		private const string s_sCommonAppOff = @"Off";
		private string m_sCommonAppOff=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sCommonAppOff']/@value")]
		public string sCommonAppOff {
			get { 
				if( m_sCommonAppOff == null){
					return s_sCommonAppOff;
				}
				return m_sCommonAppOff; 
			}
			set { 
				if( value != m_sCommonAppOff){
					m_sCommonAppOff = value;
					NotifyPropertyChanged("sCommonAppOff");
				}
			}  
		}
	


		private const string s_sCommonAppYes = @"Yes";
		private string m_sCommonAppYes=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sCommonAppYes']/@value")]
		public string sCommonAppYes {
			get { 
				if( m_sCommonAppYes == null){
					return s_sCommonAppYes;
				}
				return m_sCommonAppYes; 
			}
			set { 
				if( value != m_sCommonAppYes){
					m_sCommonAppYes = value;
					NotifyPropertyChanged("sCommonAppYes");
				}
			}  
		}
	


		private const string s_sCommonAppNo = @"No";
		private string m_sCommonAppNo=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sCommonAppNo']/@value")]
		public string sCommonAppNo {
			get { 
				if( m_sCommonAppNo == null){
					return s_sCommonAppNo;
				}
				return m_sCommonAppNo; 
			}
			set { 
				if( value != m_sCommonAppNo){
					m_sCommonAppNo = value;
					NotifyPropertyChanged("sCommonAppNo");
				}
			}  
		}
	


		private const string s_sVideoPriorityStreaming = @"Streaming";
		private string m_sVideoPriorityStreaming=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sVideoPriorityStreaming']/@value")]
		public string sVideoPriorityStreaming {
			get { 
				if( m_sVideoPriorityStreaming == null){
					return s_sVideoPriorityStreaming;
				}
				return m_sVideoPriorityStreaming; 
			}
			set { 
				if( value != m_sVideoPriorityStreaming){
					m_sVideoPriorityStreaming = value;
					NotifyPropertyChanged("sVideoPriorityStreaming");
				}
			}  
		}
	


		private const string s_sVideoPriorityAnalytics = @"Analytics";
		private string m_sVideoPriorityAnalytics=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sVideoPriorityAnalytics']/@value")]
		public string sVideoPriorityAnalytics {
			get { 
				if( m_sVideoPriorityAnalytics == null){
					return s_sVideoPriorityAnalytics;
				}
				return m_sVideoPriorityAnalytics; 
			}
			set { 
				if( value != m_sVideoPriorityAnalytics){
					m_sVideoPriorityAnalytics = value;
					NotifyPropertyChanged("sVideoPriorityAnalytics");
				}
			}  
		}
	


		private const string s_sLoadingData = @"Loading data ...";
		private string m_sLoadingData=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sLoadingData']/@value")]
		public string sLoadingData {
			get { 
				if( m_sLoadingData == null){
					return s_sLoadingData;
				}
				return m_sLoadingData; 
			}
			set { 
				if( value != m_sLoadingData){
					m_sLoadingData = value;
					NotifyPropertyChanged("sLoadingData");
				}
			}  
		}
	


		private const string s_sApplicationName = @"Network Video Console";
		private string m_sApplicationName=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sApplicationName']/@value")]
		public string sApplicationName {
			get { 
				if( m_sApplicationName == null){
					return s_sApplicationName;
				}
				return m_sApplicationName; 
			}
			set { 
				if( value != m_sApplicationName){
					m_sApplicationName = value;
					NotifyPropertyChanged("sApplicationName");
				}
			}  
		}
	


		private const string s_sDeviceControlTitle = @"Device configuration";
		private string m_sDeviceControlTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDeviceControlTitle']/@value")]
		public string sDeviceControlTitle {
			get { 
				if( m_sDeviceControlTitle == null){
					return s_sDeviceControlTitle;
				}
				return m_sDeviceControlTitle; 
			}
			set { 
				if( value != m_sDeviceControlTitle){
					m_sDeviceControlTitle = value;
					NotifyPropertyChanged("sDeviceControlTitle");
				}
			}  
		}
	


		private const string s_sDeviceControlLanguageEng = @"English";
		private string m_sDeviceControlLanguageEng=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDeviceControlLanguageEng']/@value")]
		public string sDeviceControlLanguageEng {
			get { 
				if( m_sDeviceControlLanguageEng == null){
					return s_sDeviceControlLanguageEng;
				}
				return m_sDeviceControlLanguageEng; 
			}
			set { 
				if( value != m_sDeviceControlLanguageEng){
					m_sDeviceControlLanguageEng = value;
					NotifyPropertyChanged("sDeviceControlLanguageEng");
				}
			}  
		}
	


		private const string s_sDeviceControlLanguageRus = @"Русский";
		private string m_sDeviceControlLanguageRus=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDeviceControlLanguageRus']/@value")]
		public string sDeviceControlLanguageRus {
			get { 
				if( m_sDeviceControlLanguageRus == null){
					return s_sDeviceControlLanguageRus;
				}
				return m_sDeviceControlLanguageRus; 
			}
			set { 
				if( value != m_sDeviceControlLanguageRus){
					m_sDeviceControlLanguageRus = value;
					NotifyPropertyChanged("sDeviceControlLanguageRus");
				}
			}  
		}
	


		private const string s_sDevicesListControlTitle = @"Network";
		private string m_sDevicesListControlTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDevicesListControlTitle']/@value")]
		public string sDevicesListControlTitle {
			get { 
				if( m_sDevicesListControlTitle == null){
					return s_sDevicesListControlTitle;
				}
				return m_sDevicesListControlTitle; 
			}
			set { 
				if( value != m_sDevicesListControlTitle){
					m_sDevicesListControlTitle = value;
					NotifyPropertyChanged("sDevicesListControlTitle");
				}
			}  
		}
	


		private const string s_sDevicesListControlRefresh = @"Refresh";
		private string m_sDevicesListControlRefresh=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDevicesListControlRefresh']/@value")]
		public string sDevicesListControlRefresh {
			get { 
				if( m_sDevicesListControlRefresh == null){
					return s_sDevicesListControlRefresh;
				}
				return m_sDevicesListControlRefresh; 
			}
			set { 
				if( value != m_sDevicesListControlRefresh){
					m_sDevicesListControlRefresh = value;
					NotifyPropertyChanged("sDevicesListControlRefresh");
				}
			}  
		}
	


		private const string s_sDevicesListControlColumnName = @"Name";
		private string m_sDevicesListControlColumnName=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDevicesListControlColumnName']/@value")]
		public string sDevicesListControlColumnName {
			get { 
				if( m_sDevicesListControlColumnName == null){
					return s_sDevicesListControlColumnName;
				}
				return m_sDevicesListControlColumnName; 
			}
			set { 
				if( value != m_sDevicesListControlColumnName){
					m_sDevicesListControlColumnName = value;
					NotifyPropertyChanged("sDevicesListControlColumnName");
				}
			}  
		}
	


		private const string s_sDevicesListControlColumnIPadress = @"IP Adress";
		private string m_sDevicesListControlColumnIPadress=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDevicesListControlColumnIPadress']/@value")]
		public string sDevicesListControlColumnIPadress {
			get { 
				if( m_sDevicesListControlColumnIPadress == null){
					return s_sDevicesListControlColumnIPadress;
				}
				return m_sDevicesListControlColumnIPadress; 
			}
			set { 
				if( value != m_sDevicesListControlColumnIPadress){
					m_sDevicesListControlColumnIPadress = value;
					NotifyPropertyChanged("sDevicesListControlColumnIPadress");
				}
			}  
		}
	


		private const string s_sDevicesListControlColumnType = @"Firmware";
		private string m_sDevicesListControlColumnType=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sDevicesListControlColumnType']/@value")]
		public string sDevicesListControlColumnType {
			get { 
				if( m_sDevicesListControlColumnType == null){
					return s_sDevicesListControlColumnType;
				}
				return m_sDevicesListControlColumnType; 
			}
			set { 
				if( value != m_sDevicesListControlColumnType){
					m_sDevicesListControlColumnType = value;
					NotifyPropertyChanged("sDevicesListControlColumnType");
				}
			}  
		}
	


		private const string s_constLinkButtonIdentificationAndStatus = @"Identification and status";
		private string m_constLinkButtonIdentificationAndStatus=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonIdentificationAndStatus']/@value")]
		public string constLinkButtonIdentificationAndStatus {
			get { 
				if( m_constLinkButtonIdentificationAndStatus == null){
					return s_constLinkButtonIdentificationAndStatus;
				}
				return m_constLinkButtonIdentificationAndStatus; 
			}
			set { 
				if( value != m_constLinkButtonIdentificationAndStatus){
					m_constLinkButtonIdentificationAndStatus = value;
					NotifyPropertyChanged("constLinkButtonIdentificationAndStatus");
				}
			}  
		}
	


		private const string s_constLinkButtonNetworkSettings = @"Network settings";
		private string m_constLinkButtonNetworkSettings=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonNetworkSettings']/@value")]
		public string constLinkButtonNetworkSettings {
			get { 
				if( m_constLinkButtonNetworkSettings == null){
					return s_constLinkButtonNetworkSettings;
				}
				return m_constLinkButtonNetworkSettings; 
			}
			set { 
				if( value != m_constLinkButtonNetworkSettings){
					m_constLinkButtonNetworkSettings = value;
					NotifyPropertyChanged("constLinkButtonNetworkSettings");
				}
			}  
		}
	


		private const string s_constLinkButtonDigitalIO = @"Digital IO";
		private string m_constLinkButtonDigitalIO=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonDigitalIO']/@value")]
		public string constLinkButtonDigitalIO {
			get { 
				if( m_constLinkButtonDigitalIO == null){
					return s_constLinkButtonDigitalIO;
				}
				return m_constLinkButtonDigitalIO; 
			}
			set { 
				if( value != m_constLinkButtonDigitalIO){
					m_constLinkButtonDigitalIO = value;
					NotifyPropertyChanged("constLinkButtonDigitalIO");
				}
			}  
		}
	


		private const string s_constLinkButtonMaintenance = @"Maintenance";
		private string m_constLinkButtonMaintenance=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonMaintenance']/@value")]
		public string constLinkButtonMaintenance {
			get { 
				if( m_constLinkButtonMaintenance == null){
					return s_constLinkButtonMaintenance;
				}
				return m_constLinkButtonMaintenance; 
			}
			set { 
				if( value != m_constLinkButtonMaintenance){
					m_constLinkButtonMaintenance = value;
					NotifyPropertyChanged("constLinkButtonMaintenance");
				}
			}  
		}
	


		private const string s_constLinkButtonLiveVideo = @"Live video";
		private string m_constLinkButtonLiveVideo=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonLiveVideo']/@value")]
		public string constLinkButtonLiveVideo {
			get { 
				if( m_constLinkButtonLiveVideo == null){
					return s_constLinkButtonLiveVideo;
				}
				return m_constLinkButtonLiveVideo; 
			}
			set { 
				if( value != m_constLinkButtonLiveVideo){
					m_constLinkButtonLiveVideo = value;
					NotifyPropertyChanged("constLinkButtonLiveVideo");
				}
			}  
		}
	


		private const string s_constLinkButtonEvents = @"Events";
		private string m_constLinkButtonEvents=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonEvents']/@value")]
		public string constLinkButtonEvents {
			get { 
				if( m_constLinkButtonEvents == null){
					return s_constLinkButtonEvents;
				}
				return m_constLinkButtonEvents; 
			}
			set { 
				if( value != m_constLinkButtonEvents){
					m_constLinkButtonEvents = value;
					NotifyPropertyChanged("constLinkButtonEvents");
				}
			}  
		}
	


		private const string s_constLinkButtonDepthCalibration = @"Depth calibration";
		private string m_constLinkButtonDepthCalibration=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonDepthCalibration']/@value")]
		public string constLinkButtonDepthCalibration {
			get { 
				if( m_constLinkButtonDepthCalibration == null){
					return s_constLinkButtonDepthCalibration;
				}
				return m_constLinkButtonDepthCalibration; 
			}
			set { 
				if( value != m_constLinkButtonDepthCalibration){
					m_constLinkButtonDepthCalibration = value;
					NotifyPropertyChanged("constLinkButtonDepthCalibration");
				}
			}  
		}
	


		private const string s_constLinkButtonVideoStreaming = @"Video streaming";
		private string m_constLinkButtonVideoStreaming=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonVideoStreaming']/@value")]
		public string constLinkButtonVideoStreaming {
			get { 
				if( m_constLinkButtonVideoStreaming == null){
					return s_constLinkButtonVideoStreaming;
				}
				return m_constLinkButtonVideoStreaming; 
			}
			set { 
				if( value != m_constLinkButtonVideoStreaming){
					m_constLinkButtonVideoStreaming = value;
					NotifyPropertyChanged("constLinkButtonVideoStreaming");
				}
			}  
		}
	


		private const string s_constLinkButtonDisplayAnnotation = @"Display  annotation";
		private string m_constLinkButtonDisplayAnnotation=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonDisplayAnnotation']/@value")]
		public string constLinkButtonDisplayAnnotation {
			get { 
				if( m_constLinkButtonDisplayAnnotation == null){
					return s_constLinkButtonDisplayAnnotation;
				}
				return m_constLinkButtonDisplayAnnotation; 
			}
			set { 
				if( value != m_constLinkButtonDisplayAnnotation){
					m_constLinkButtonDisplayAnnotation = value;
					NotifyPropertyChanged("constLinkButtonDisplayAnnotation");
				}
			}  
		}
	


		private const string s_constLinkButtonTamperingDetectors = @"Tampering detectors";
		private string m_constLinkButtonTamperingDetectors=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonTamperingDetectors']/@value")]
		public string constLinkButtonTamperingDetectors {
			get { 
				if( m_constLinkButtonTamperingDetectors == null){
					return s_constLinkButtonTamperingDetectors;
				}
				return m_constLinkButtonTamperingDetectors; 
			}
			set { 
				if( value != m_constLinkButtonTamperingDetectors){
					m_constLinkButtonTamperingDetectors = value;
					NotifyPropertyChanged("constLinkButtonTamperingDetectors");
				}
			}  
		}
	


		private const string s_constLinkButtonObjectTracker = @"Object tracker";
		private string m_constLinkButtonObjectTracker=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonObjectTracker']/@value")]
		public string constLinkButtonObjectTracker {
			get { 
				if( m_constLinkButtonObjectTracker == null){
					return s_constLinkButtonObjectTracker;
				}
				return m_constLinkButtonObjectTracker; 
			}
			set { 
				if( value != m_constLinkButtonObjectTracker){
					m_constLinkButtonObjectTracker = value;
					NotifyPropertyChanged("constLinkButtonObjectTracker");
				}
			}  
		}
	


		private const string s_constLinkButtonRuleEngine = @"Rule engine";
		private string m_constLinkButtonRuleEngine=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonRuleEngine']/@value")]
		public string constLinkButtonRuleEngine {
			get { 
				if( m_constLinkButtonRuleEngine == null){
					return s_constLinkButtonRuleEngine;
				}
				return m_constLinkButtonRuleEngine; 
			}
			set { 
				if( value != m_constLinkButtonRuleEngine){
					m_constLinkButtonRuleEngine = value;
					NotifyPropertyChanged("constLinkButtonRuleEngine");
				}
			}  
		}
	


		private const string s_constLinkButtonAntishaker = @"Antishaker";
		private string m_constLinkButtonAntishaker=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonAntishaker']/@value")]
		public string constLinkButtonAntishaker {
			get { 
				if( m_constLinkButtonAntishaker == null){
					return s_constLinkButtonAntishaker;
				}
				return m_constLinkButtonAntishaker; 
			}
			set { 
				if( value != m_constLinkButtonAntishaker){
					m_constLinkButtonAntishaker = value;
					NotifyPropertyChanged("constLinkButtonAntishaker");
				}
			}  
		}
	


		private const string s_constLinkButtonRotation = @"Rotation";
		private string m_constLinkButtonRotation=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='constLinkButtonRotation']/@value")]
		public string constLinkButtonRotation {
			get { 
				if( m_constLinkButtonRotation == null){
					return s_constLinkButtonRotation;
				}
				return m_constLinkButtonRotation; 
			}
			set { 
				if( value != m_constLinkButtonRotation){
					m_constLinkButtonRotation = value;
					NotifyPropertyChanged("constLinkButtonRotation");
				}
			}  
		}
	


		private const string s_sButtonSave = @"Save";
		private string m_sButtonSave=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sButtonSave']/@value")]
		public string sButtonSave {
			get { 
				if( m_sButtonSave == null){
					return s_sButtonSave;
				}
				return m_sButtonSave; 
			}
			set { 
				if( value != m_sButtonSave){
					m_sButtonSave = value;
					NotifyPropertyChanged("sButtonSave");
				}
			}  
		}
	


		private const string s_sButtonCancel = @"Cancel";
		private string m_sButtonCancel=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sButtonCancel']/@value")]
		public string sButtonCancel {
			get { 
				if( m_sButtonCancel == null){
					return s_sButtonCancel;
				}
				return m_sButtonCancel; 
			}
			set { 
				if( value != m_sButtonCancel){
					m_sButtonCancel = value;
					NotifyPropertyChanged("sButtonCancel");
				}
			}  
		}
	


		private const string s_sButtonClose = @"Close";
		private string m_sButtonClose=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sButtonClose']/@value")]
		public string sButtonClose {
			get { 
				if( m_sButtonClose == null){
					return s_sButtonClose;
				}
				return m_sButtonClose; 
			}
			set { 
				if( value != m_sButtonClose){
					m_sButtonClose = value;
					NotifyPropertyChanged("sButtonClose");
				}
			}  
		}
	


		private const string s_sNotifierTextTitle = @"No connected devices.";
		private string m_sNotifierTextTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sNotifierTextTitle']/@value")]
		public string sNotifierTextTitle {
			get { 
				if( m_sNotifierTextTitle == null){
					return s_sNotifierTextTitle;
				}
				return m_sNotifierTextTitle; 
			}
			set { 
				if( value != m_sNotifierTextTitle){
					m_sNotifierTextTitle = value;
					NotifyPropertyChanged("sNotifierTextTitle");
				}
			}  
		}
	


		private const string s_sNotifierText = @"Please check the device is properly connected, or contact support.";
		private string m_sNotifierText=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sNotifierText']/@value")]
		public string sNotifierText {
			get { 
				if( m_sNotifierText == null){
					return s_sNotifierText;
				}
				return m_sNotifierText; 
			}
			set { 
				if( value != m_sNotifierText){
					m_sNotifierText = value;
					NotifyPropertyChanged("sNotifierText");
				}
			}  
		}
	


		private const string s_sNotifierTextContacts = @"";
		private string m_sNotifierTextContacts=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sNotifierTextContacts']/@value")]
		public string sNotifierTextContacts {
			get { 
				if( m_sNotifierTextContacts == null){
					return s_sNotifierTextContacts;
				}
				return m_sNotifierTextContacts; 
			}
			set { 
				if( value != m_sNotifierTextContacts){
					m_sNotifierTextContacts = value;
					NotifyPropertyChanged("sNotifierTextContacts");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusTitle = @"Device identification and status";
		private string m_sPropertyDeviceInfoStatusTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusTitle']/@value")]
		public string sPropertyDeviceInfoStatusTitle {
			get { 
				if( m_sPropertyDeviceInfoStatusTitle == null){
					return s_sPropertyDeviceInfoStatusTitle;
				}
				return m_sPropertyDeviceInfoStatusTitle; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusTitle){
					m_sPropertyDeviceInfoStatusTitle = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusTitle");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableName = @"Name";
		private string m_sPropertyDeviceInfoStatusLableName=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableName']/@value")]
		public string sPropertyDeviceInfoStatusLableName {
			get { 
				if( m_sPropertyDeviceInfoStatusLableName == null){
					return s_sPropertyDeviceInfoStatusLableName;
				}
				return m_sPropertyDeviceInfoStatusLableName; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableName){
					m_sPropertyDeviceInfoStatusLableName = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableName");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableDeviceID = @"Device ID";
		private string m_sPropertyDeviceInfoStatusLableDeviceID=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableDeviceID']/@value")]
		public string sPropertyDeviceInfoStatusLableDeviceID {
			get { 
				if( m_sPropertyDeviceInfoStatusLableDeviceID == null){
					return s_sPropertyDeviceInfoStatusLableDeviceID;
				}
				return m_sPropertyDeviceInfoStatusLableDeviceID; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableDeviceID){
					m_sPropertyDeviceInfoStatusLableDeviceID = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableDeviceID");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableFirmware = @"Firmware";
		private string m_sPropertyDeviceInfoStatusLableFirmware=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableFirmware']/@value")]
		public string sPropertyDeviceInfoStatusLableFirmware {
			get { 
				if( m_sPropertyDeviceInfoStatusLableFirmware == null){
					return s_sPropertyDeviceInfoStatusLableFirmware;
				}
				return m_sPropertyDeviceInfoStatusLableFirmware; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableFirmware){
					m_sPropertyDeviceInfoStatusLableFirmware = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableFirmware");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableHardware = @"Hardware";
		private string m_sPropertyDeviceInfoStatusLableHardware=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableHardware']/@value")]
		public string sPropertyDeviceInfoStatusLableHardware {
			get { 
				if( m_sPropertyDeviceInfoStatusLableHardware == null){
					return s_sPropertyDeviceInfoStatusLableHardware;
				}
				return m_sPropertyDeviceInfoStatusLableHardware; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableHardware){
					m_sPropertyDeviceInfoStatusLableHardware = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableHardware");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableVersion = @"Version";
		private string m_sPropertyDeviceInfoStatusLableVersion=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableVersion']/@value")]
		public string sPropertyDeviceInfoStatusLableVersion {
			get { 
				if( m_sPropertyDeviceInfoStatusLableVersion == null){
					return s_sPropertyDeviceInfoStatusLableVersion;
				}
				return m_sPropertyDeviceInfoStatusLableVersion; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableVersion){
					m_sPropertyDeviceInfoStatusLableVersion = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableVersion");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableIPAddr = @"IP address";
		private string m_sPropertyDeviceInfoStatusLableIPAddr=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableIPAddr']/@value")]
		public string sPropertyDeviceInfoStatusLableIPAddr {
			get { 
				if( m_sPropertyDeviceInfoStatusLableIPAddr == null){
					return s_sPropertyDeviceInfoStatusLableIPAddr;
				}
				return m_sPropertyDeviceInfoStatusLableIPAddr; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableIPAddr){
					m_sPropertyDeviceInfoStatusLableIPAddr = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableIPAddr");
				}
			}  
		}
	


		private const string s_sPropertyDeviceInfoStatusLableMACAddr = @"MAC address";
		private string m_sPropertyDeviceInfoStatusLableMACAddr=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDeviceInfoStatusLableMACAddr']/@value")]
		public string sPropertyDeviceInfoStatusLableMACAddr {
			get { 
				if( m_sPropertyDeviceInfoStatusLableMACAddr == null){
					return s_sPropertyDeviceInfoStatusLableMACAddr;
				}
				return m_sPropertyDeviceInfoStatusLableMACAddr; 
			}
			set { 
				if( value != m_sPropertyDeviceInfoStatusLableMACAddr){
					m_sPropertyDeviceInfoStatusLableMACAddr = value;
					NotifyPropertyChanged("sPropertyDeviceInfoStatusLableMACAddr");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsTitle = @"Network settings";
		private string m_sPropertyNetworkSettingsTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsTitle']/@value")]
		public string sPropertyNetworkSettingsTitle {
			get { 
				if( m_sPropertyNetworkSettingsTitle == null){
					return s_sPropertyNetworkSettingsTitle;
				}
				return m_sPropertyNetworkSettingsTitle; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsTitle){
					m_sPropertyNetworkSettingsTitle = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsTitle");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsDHCP = @"DHCP";
		private string m_sPropertyNetworkSettingsDHCP=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsDHCP']/@value")]
		public string sPropertyNetworkSettingsDHCP {
			get { 
				if( m_sPropertyNetworkSettingsDHCP == null){
					return s_sPropertyNetworkSettingsDHCP;
				}
				return m_sPropertyNetworkSettingsDHCP; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsDHCP){
					m_sPropertyNetworkSettingsDHCP = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsDHCP");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsIPaddr = @"Device IP address ";
		private string m_sPropertyNetworkSettingsIPaddr=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsIPaddr']/@value")]
		public string sPropertyNetworkSettingsIPaddr {
			get { 
				if( m_sPropertyNetworkSettingsIPaddr == null){
					return s_sPropertyNetworkSettingsIPaddr;
				}
				return m_sPropertyNetworkSettingsIPaddr; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsIPaddr){
					m_sPropertyNetworkSettingsIPaddr = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsIPaddr");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsSubnetMask = @"Subnet mask";
		private string m_sPropertyNetworkSettingsSubnetMask=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsSubnetMask']/@value")]
		public string sPropertyNetworkSettingsSubnetMask {
			get { 
				if( m_sPropertyNetworkSettingsSubnetMask == null){
					return s_sPropertyNetworkSettingsSubnetMask;
				}
				return m_sPropertyNetworkSettingsSubnetMask; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsSubnetMask){
					m_sPropertyNetworkSettingsSubnetMask = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsSubnetMask");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsGateAddr = @"Gateway address";
		private string m_sPropertyNetworkSettingsGateAddr=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsGateAddr']/@value")]
		public string sPropertyNetworkSettingsGateAddr {
			get { 
				if( m_sPropertyNetworkSettingsGateAddr == null){
					return s_sPropertyNetworkSettingsGateAddr;
				}
				return m_sPropertyNetworkSettingsGateAddr; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsGateAddr){
					m_sPropertyNetworkSettingsGateAddr = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsGateAddr");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsDNSaddr = @"DNS address";
		private string m_sPropertyNetworkSettingsDNSaddr=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsDNSaddr']/@value")]
		public string sPropertyNetworkSettingsDNSaddr {
			get { 
				if( m_sPropertyNetworkSettingsDNSaddr == null){
					return s_sPropertyNetworkSettingsDNSaddr;
				}
				return m_sPropertyNetworkSettingsDNSaddr; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsDNSaddr){
					m_sPropertyNetworkSettingsDNSaddr = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsDNSaddr");
				}
			}  
		}
	


		private const string s_sPropertyNetworkSettingsMACaddr = @"MAC address";
		private string m_sPropertyNetworkSettingsMACaddr=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyNetworkSettingsMACaddr']/@value")]
		public string sPropertyNetworkSettingsMACaddr {
			get { 
				if( m_sPropertyNetworkSettingsMACaddr == null){
					return s_sPropertyNetworkSettingsMACaddr;
				}
				return m_sPropertyNetworkSettingsMACaddr; 
			}
			set { 
				if( value != m_sPropertyNetworkSettingsMACaddr){
					m_sPropertyNetworkSettingsMACaddr = value;
					NotifyPropertyChanged("sPropertyNetworkSettingsMACaddr");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOTitle = @"Digital IO";
		private string m_sPropertyDigitalIOTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOTitle']/@value")]
		public string sPropertyDigitalIOTitle {
			get { 
				if( m_sPropertyDigitalIOTitle == null){
					return s_sPropertyDigitalIOTitle;
				}
				return m_sPropertyDigitalIOTitle; 
			}
			set { 
				if( value != m_sPropertyDigitalIOTitle){
					m_sPropertyDigitalIOTitle = value;
					NotifyPropertyChanged("sPropertyDigitalIOTitle");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOInputName = @"Name";
		private string m_sPropertyDigitalIOInputName=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOInputName']/@value")]
		public string sPropertyDigitalIOInputName {
			get { 
				if( m_sPropertyDigitalIOInputName == null){
					return s_sPropertyDigitalIOInputName;
				}
				return m_sPropertyDigitalIOInputName; 
			}
			set { 
				if( value != m_sPropertyDigitalIOInputName){
					m_sPropertyDigitalIOInputName = value;
					NotifyPropertyChanged("sPropertyDigitalIOInputName");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOInputNormalStatus = @"Normal status";
		private string m_sPropertyDigitalIOInputNormalStatus=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOInputNormalStatus']/@value")]
		public string sPropertyDigitalIOInputNormalStatus {
			get { 
				if( m_sPropertyDigitalIOInputNormalStatus == null){
					return s_sPropertyDigitalIOInputNormalStatus;
				}
				return m_sPropertyDigitalIOInputNormalStatus; 
			}
			set { 
				if( value != m_sPropertyDigitalIOInputNormalStatus){
					m_sPropertyDigitalIOInputNormalStatus = value;
					NotifyPropertyChanged("sPropertyDigitalIOInputNormalStatus");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOInputCurrentStatus = @"Current status";
		private string m_sPropertyDigitalIOInputCurrentStatus=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOInputCurrentStatus']/@value")]
		public string sPropertyDigitalIOInputCurrentStatus {
			get { 
				if( m_sPropertyDigitalIOInputCurrentStatus == null){
					return s_sPropertyDigitalIOInputCurrentStatus;
				}
				return m_sPropertyDigitalIOInputCurrentStatus; 
			}
			set { 
				if( value != m_sPropertyDigitalIOInputCurrentStatus){
					m_sPropertyDigitalIOInputCurrentStatus = value;
					NotifyPropertyChanged("sPropertyDigitalIOInputCurrentStatus");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOOutputName = @"Name";
		private string m_sPropertyDigitalIOOutputName=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOOutputName']/@value")]
		public string sPropertyDigitalIOOutputName {
			get { 
				if( m_sPropertyDigitalIOOutputName == null){
					return s_sPropertyDigitalIOOutputName;
				}
				return m_sPropertyDigitalIOOutputName; 
			}
			set { 
				if( value != m_sPropertyDigitalIOOutputName){
					m_sPropertyDigitalIOOutputName = value;
					NotifyPropertyChanged("sPropertyDigitalIOOutputName");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOOutputIdleStatus = @"Idle status";
		private string m_sPropertyDigitalIOOutputIdleStatus=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOOutputIdleStatus']/@value")]
		public string sPropertyDigitalIOOutputIdleStatus {
			get { 
				if( m_sPropertyDigitalIOOutputIdleStatus == null){
					return s_sPropertyDigitalIOOutputIdleStatus;
				}
				return m_sPropertyDigitalIOOutputIdleStatus; 
			}
			set { 
				if( value != m_sPropertyDigitalIOOutputIdleStatus){
					m_sPropertyDigitalIOOutputIdleStatus = value;
					NotifyPropertyChanged("sPropertyDigitalIOOutputIdleStatus");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOOutputCurrentStatus = @"Current status";
		private string m_sPropertyDigitalIOOutputCurrentStatus=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOOutputCurrentStatus']/@value")]
		public string sPropertyDigitalIOOutputCurrentStatus {
			get { 
				if( m_sPropertyDigitalIOOutputCurrentStatus == null){
					return s_sPropertyDigitalIOOutputCurrentStatus;
				}
				return m_sPropertyDigitalIOOutputCurrentStatus; 
			}
			set { 
				if( value != m_sPropertyDigitalIOOutputCurrentStatus){
					m_sPropertyDigitalIOOutputCurrentStatus = value;
					NotifyPropertyChanged("sPropertyDigitalIOOutputCurrentStatus");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOInputs = @"Digital inputs";
		private string m_sPropertyDigitalIOInputs=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOInputs']/@value")]
		public string sPropertyDigitalIOInputs {
			get { 
				if( m_sPropertyDigitalIOInputs == null){
					return s_sPropertyDigitalIOInputs;
				}
				return m_sPropertyDigitalIOInputs; 
			}
			set { 
				if( value != m_sPropertyDigitalIOInputs){
					m_sPropertyDigitalIOInputs = value;
					NotifyPropertyChanged("sPropertyDigitalIOInputs");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOOutputs = @"Digital outputs (relays)";
		private string m_sPropertyDigitalIOOutputs=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOOutputs']/@value")]
		public string sPropertyDigitalIOOutputs {
			get { 
				if( m_sPropertyDigitalIOOutputs == null){
					return s_sPropertyDigitalIOOutputs;
				}
				return m_sPropertyDigitalIOOutputs; 
			}
			set { 
				if( value != m_sPropertyDigitalIOOutputs){
					m_sPropertyDigitalIOOutputs = value;
					NotifyPropertyChanged("sPropertyDigitalIOOutputs");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOEventAction = @"Event action";
		private string m_sPropertyDigitalIOEventAction=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOEventAction']/@value")]
		public string sPropertyDigitalIOEventAction {
			get { 
				if( m_sPropertyDigitalIOEventAction == null){
					return s_sPropertyDigitalIOEventAction;
				}
				return m_sPropertyDigitalIOEventAction; 
			}
			set { 
				if( value != m_sPropertyDigitalIOEventAction){
					m_sPropertyDigitalIOEventAction = value;
					NotifyPropertyChanged("sPropertyDigitalIOEventAction");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOEventSendONVIFmessage = @"Send ONVIF message";
		private string m_sPropertyDigitalIOEventSendONVIFmessage=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOEventSendONVIFmessage']/@value")]
		public string sPropertyDigitalIOEventSendONVIFmessage {
			get { 
				if( m_sPropertyDigitalIOEventSendONVIFmessage == null){
					return s_sPropertyDigitalIOEventSendONVIFmessage;
				}
				return m_sPropertyDigitalIOEventSendONVIFmessage; 
			}
			set { 
				if( value != m_sPropertyDigitalIOEventSendONVIFmessage){
					m_sPropertyDigitalIOEventSendONVIFmessage = value;
					NotifyPropertyChanged("sPropertyDigitalIOEventSendONVIFmessage");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOTriggerRelay = @"Trigger relay";
		private string m_sPropertyDigitalIOTriggerRelay=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOTriggerRelay']/@value")]
		public string sPropertyDigitalIOTriggerRelay {
			get { 
				if( m_sPropertyDigitalIOTriggerRelay == null){
					return s_sPropertyDigitalIOTriggerRelay;
				}
				return m_sPropertyDigitalIOTriggerRelay; 
			}
			set { 
				if( value != m_sPropertyDigitalIOTriggerRelay){
					m_sPropertyDigitalIOTriggerRelay = value;
					NotifyPropertyChanged("sPropertyDigitalIOTriggerRelay");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIORecordChannel = @"Record channel";
		private string m_sPropertyDigitalIORecordChannel=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIORecordChannel']/@value")]
		public string sPropertyDigitalIORecordChannel {
			get { 
				if( m_sPropertyDigitalIORecordChannel == null){
					return s_sPropertyDigitalIORecordChannel;
				}
				return m_sPropertyDigitalIORecordChannel; 
			}
			set { 
				if( value != m_sPropertyDigitalIORecordChannel){
					m_sPropertyDigitalIORecordChannel = value;
					NotifyPropertyChanged("sPropertyDigitalIORecordChannel");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOSwitchAnalogue = @"Switch analogue video on";
		private string m_sPropertyDigitalIOSwitchAnalogue=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOSwitchAnalogue']/@value")]
		public string sPropertyDigitalIOSwitchAnalogue {
			get { 
				if( m_sPropertyDigitalIOSwitchAnalogue == null){
					return s_sPropertyDigitalIOSwitchAnalogue;
				}
				return m_sPropertyDigitalIOSwitchAnalogue; 
			}
			set { 
				if( value != m_sPropertyDigitalIOSwitchAnalogue){
					m_sPropertyDigitalIOSwitchAnalogue = value;
					NotifyPropertyChanged("sPropertyDigitalIOSwitchAnalogue");
				}
			}  
		}
	


		private const string s_sPropertyDigitalIOButtonTriggerRelay = @"Trigger relay";
		private string m_sPropertyDigitalIOButtonTriggerRelay=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyDigitalIOButtonTriggerRelay']/@value")]
		public string sPropertyDigitalIOButtonTriggerRelay {
			get { 
				if( m_sPropertyDigitalIOButtonTriggerRelay == null){
					return s_sPropertyDigitalIOButtonTriggerRelay;
				}
				return m_sPropertyDigitalIOButtonTriggerRelay; 
			}
			set { 
				if( value != m_sPropertyDigitalIOButtonTriggerRelay){
					m_sPropertyDigitalIOButtonTriggerRelay = value;
					NotifyPropertyChanged("sPropertyDigitalIOButtonTriggerRelay");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceTitle = @"Maintenance";
		private string m_sPropertyMaintenanceTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceTitle']/@value")]
		public string sPropertyMaintenanceTitle {
			get { 
				if( m_sPropertyMaintenanceTitle == null){
					return s_sPropertyMaintenanceTitle;
				}
				return m_sPropertyMaintenanceTitle; 
			}
			set { 
				if( value != m_sPropertyMaintenanceTitle){
					m_sPropertyMaintenanceTitle = value;
					NotifyPropertyChanged("sPropertyMaintenanceTitle");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceConfiguration = @"Configuration";
		private string m_sPropertyMaintenanceConfiguration=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceConfiguration']/@value")]
		public string sPropertyMaintenanceConfiguration {
			get { 
				if( m_sPropertyMaintenanceConfiguration == null){
					return s_sPropertyMaintenanceConfiguration;
				}
				return m_sPropertyMaintenanceConfiguration; 
			}
			set { 
				if( value != m_sPropertyMaintenanceConfiguration){
					m_sPropertyMaintenanceConfiguration = value;
					NotifyPropertyChanged("sPropertyMaintenanceConfiguration");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceBTNBackup = @"Backup";
		private string m_sPropertyMaintenanceBTNBackup=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceBTNBackup']/@value")]
		public string sPropertyMaintenanceBTNBackup {
			get { 
				if( m_sPropertyMaintenanceBTNBackup == null){
					return s_sPropertyMaintenanceBTNBackup;
				}
				return m_sPropertyMaintenanceBTNBackup; 
			}
			set { 
				if( value != m_sPropertyMaintenanceBTNBackup){
					m_sPropertyMaintenanceBTNBackup = value;
					NotifyPropertyChanged("sPropertyMaintenanceBTNBackup");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceBTNRestore = @"Restore";
		private string m_sPropertyMaintenanceBTNRestore=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceBTNRestore']/@value")]
		public string sPropertyMaintenanceBTNRestore {
			get { 
				if( m_sPropertyMaintenanceBTNRestore == null){
					return s_sPropertyMaintenanceBTNRestore;
				}
				return m_sPropertyMaintenanceBTNRestore; 
			}
			set { 
				if( value != m_sPropertyMaintenanceBTNRestore){
					m_sPropertyMaintenanceBTNRestore = value;
					NotifyPropertyChanged("sPropertyMaintenanceBTNRestore");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceFactoryReset = @"Factory reset";
		private string m_sPropertyMaintenanceFactoryReset=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceFactoryReset']/@value")]
		public string sPropertyMaintenanceFactoryReset {
			get { 
				if( m_sPropertyMaintenanceFactoryReset == null){
					return s_sPropertyMaintenanceFactoryReset;
				}
				return m_sPropertyMaintenanceFactoryReset; 
			}
			set { 
				if( value != m_sPropertyMaintenanceFactoryReset){
					m_sPropertyMaintenanceFactoryReset = value;
					NotifyPropertyChanged("sPropertyMaintenanceFactoryReset");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceBTNSoftReset = @"Soft reset";
		private string m_sPropertyMaintenanceBTNSoftReset=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceBTNSoftReset']/@value")]
		public string sPropertyMaintenanceBTNSoftReset {
			get { 
				if( m_sPropertyMaintenanceBTNSoftReset == null){
					return s_sPropertyMaintenanceBTNSoftReset;
				}
				return m_sPropertyMaintenanceBTNSoftReset; 
			}
			set { 
				if( value != m_sPropertyMaintenanceBTNSoftReset){
					m_sPropertyMaintenanceBTNSoftReset = value;
					NotifyPropertyChanged("sPropertyMaintenanceBTNSoftReset");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceBTNHardReset = @"Hard reset";
		private string m_sPropertyMaintenanceBTNHardReset=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceBTNHardReset']/@value")]
		public string sPropertyMaintenanceBTNHardReset {
			get { 
				if( m_sPropertyMaintenanceBTNHardReset == null){
					return s_sPropertyMaintenanceBTNHardReset;
				}
				return m_sPropertyMaintenanceBTNHardReset; 
			}
			set { 
				if( value != m_sPropertyMaintenanceBTNHardReset){
					m_sPropertyMaintenanceBTNHardReset = value;
					NotifyPropertyChanged("sPropertyMaintenanceBTNHardReset");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceDiagnostics = @"Diagnostics and support";
		private string m_sPropertyMaintenanceDiagnostics=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceDiagnostics']/@value")]
		public string sPropertyMaintenanceDiagnostics {
			get { 
				if( m_sPropertyMaintenanceDiagnostics == null){
					return s_sPropertyMaintenanceDiagnostics;
				}
				return m_sPropertyMaintenanceDiagnostics; 
			}
			set { 
				if( value != m_sPropertyMaintenanceDiagnostics){
					m_sPropertyMaintenanceDiagnostics = value;
					NotifyPropertyChanged("sPropertyMaintenanceDiagnostics");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceBTNDownloadDump = @"Download Dump";
		private string m_sPropertyMaintenanceBTNDownloadDump=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceBTNDownloadDump']/@value")]
		public string sPropertyMaintenanceBTNDownloadDump {
			get { 
				if( m_sPropertyMaintenanceBTNDownloadDump == null){
					return s_sPropertyMaintenanceBTNDownloadDump;
				}
				return m_sPropertyMaintenanceBTNDownloadDump; 
			}
			set { 
				if( value != m_sPropertyMaintenanceBTNDownloadDump){
					m_sPropertyMaintenanceBTNDownloadDump = value;
					NotifyPropertyChanged("sPropertyMaintenanceBTNDownloadDump");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceFirmwareVer = @"Current firmware version";
		private string m_sPropertyMaintenanceFirmwareVer=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceFirmwareVer']/@value")]
		public string sPropertyMaintenanceFirmwareVer {
			get { 
				if( m_sPropertyMaintenanceFirmwareVer == null){
					return s_sPropertyMaintenanceFirmwareVer;
				}
				return m_sPropertyMaintenanceFirmwareVer; 
			}
			set { 
				if( value != m_sPropertyMaintenanceFirmwareVer){
					m_sPropertyMaintenanceFirmwareVer = value;
					NotifyPropertyChanged("sPropertyMaintenanceFirmwareVer");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceUpgrateFirmware = @"Upgrade firmware";
		private string m_sPropertyMaintenanceUpgrateFirmware=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceUpgrateFirmware']/@value")]
		public string sPropertyMaintenanceUpgrateFirmware {
			get { 
				if( m_sPropertyMaintenanceUpgrateFirmware == null){
					return s_sPropertyMaintenanceUpgrateFirmware;
				}
				return m_sPropertyMaintenanceUpgrateFirmware; 
			}
			set { 
				if( value != m_sPropertyMaintenanceUpgrateFirmware){
					m_sPropertyMaintenanceUpgrateFirmware = value;
					NotifyPropertyChanged("sPropertyMaintenanceUpgrateFirmware");
				}
			}  
		}
	


		private const string s_sPropertyMaintenanceBTNUpgrate = @"Upgrate";
		private string m_sPropertyMaintenanceBTNUpgrate=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyMaintenanceBTNUpgrate']/@value")]
		public string sPropertyMaintenanceBTNUpgrate {
			get { 
				if( m_sPropertyMaintenanceBTNUpgrate == null){
					return s_sPropertyMaintenanceBTNUpgrate;
				}
				return m_sPropertyMaintenanceBTNUpgrate; 
			}
			set { 
				if( value != m_sPropertyMaintenanceBTNUpgrate){
					m_sPropertyMaintenanceBTNUpgrate = value;
					NotifyPropertyChanged("sPropertyMaintenanceBTNUpgrate");
				}
			}  
		}
	


		private const string s_sPropertyLiveVideoTitle = @"Live video";
		private string m_sPropertyLiveVideoTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyLiveVideoTitle']/@value")]
		public string sPropertyLiveVideoTitle {
			get { 
				if( m_sPropertyLiveVideoTitle == null){
					return s_sPropertyLiveVideoTitle;
				}
				return m_sPropertyLiveVideoTitle; 
			}
			set { 
				if( value != m_sPropertyLiveVideoTitle){
					m_sPropertyLiveVideoTitle = value;
					NotifyPropertyChanged("sPropertyLiveVideoTitle");
				}
			}  
		}
	


		private const string s_sPropertyEventsTitle = @"Events";
		private string m_sPropertyEventsTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyEventsTitle']/@value")]
		public string sPropertyEventsTitle {
			get { 
				if( m_sPropertyEventsTitle == null){
					return s_sPropertyEventsTitle;
				}
				return m_sPropertyEventsTitle; 
			}
			set { 
				if( value != m_sPropertyEventsTitle){
					m_sPropertyEventsTitle = value;
					NotifyPropertyChanged("sPropertyEventsTitle");
				}
			}  
		}
	


		private const string s_sPropertyEventsColumnID = @"Rule ID";
		private string m_sPropertyEventsColumnID=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyEventsColumnID']/@value")]
		public string sPropertyEventsColumnID {
			get { 
				if( m_sPropertyEventsColumnID == null){
					return s_sPropertyEventsColumnID;
				}
				return m_sPropertyEventsColumnID; 
			}
			set { 
				if( value != m_sPropertyEventsColumnID){
					m_sPropertyEventsColumnID = value;
					NotifyPropertyChanged("sPropertyEventsColumnID");
				}
			}  
		}
	


		private const string s_sPropertyEventsColumnDate = @"Date/Time";
		private string m_sPropertyEventsColumnDate=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyEventsColumnDate']/@value")]
		public string sPropertyEventsColumnDate {
			get { 
				if( m_sPropertyEventsColumnDate == null){
					return s_sPropertyEventsColumnDate;
				}
				return m_sPropertyEventsColumnDate; 
			}
			set { 
				if( value != m_sPropertyEventsColumnDate){
					m_sPropertyEventsColumnDate = value;
					NotifyPropertyChanged("sPropertyEventsColumnDate");
				}
			}  
		}
	


		private const string s_sPropertyEventsColumnType = @"Type";
		private string m_sPropertyEventsColumnType=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyEventsColumnType']/@value")]
		public string sPropertyEventsColumnType {
			get { 
				if( m_sPropertyEventsColumnType == null){
					return s_sPropertyEventsColumnType;
				}
				return m_sPropertyEventsColumnType; 
			}
			set { 
				if( value != m_sPropertyEventsColumnType){
					m_sPropertyEventsColumnType = value;
					NotifyPropertyChanged("sPropertyEventsColumnType");
				}
			}  
		}
	


		private const string s_sPropertyEventsColumnDetails = @"Details";
		private string m_sPropertyEventsColumnDetails=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyEventsColumnDetails']/@value")]
		public string sPropertyEventsColumnDetails {
			get { 
				if( m_sPropertyEventsColumnDetails == null){
					return s_sPropertyEventsColumnDetails;
				}
				return m_sPropertyEventsColumnDetails; 
			}
			set { 
				if( value != m_sPropertyEventsColumnDetails){
					m_sPropertyEventsColumnDetails = value;
					NotifyPropertyChanged("sPropertyEventsColumnDetails");
				}
			}  
		}
	


		private const string s_sPropertyVideoStreamingTitle = @"Video streaming";
		private string m_sPropertyVideoStreamingTitle=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyVideoStreamingTitle']/@value")]
		public string sPropertyVideoStreamingTitle {
			get { 
				if( m_sPropertyVideoStreamingTitle == null){
					return s_sPropertyVideoStreamingTitle;
				}
				return m_sPropertyVideoStreamingTitle; 
			}
			set { 
				if( value != m_sPropertyVideoStreamingTitle){
					m_sPropertyVideoStreamingTitle = value;
					NotifyPropertyChanged("sPropertyVideoStreamingTitle");
				}
			}  
		}
	


		private const string s_sPropertyVideoStreamingResolution = @"Resolution, pixels";
		private string m_sPropertyVideoStreamingResolution=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyVideoStreamingResolution']/@value")]
		public string sPropertyVideoStreamingResolution {
			get { 
				if( m_sPropertyVideoStreamingResolution == null){
					return s_sPropertyVideoStreamingResolution;
				}
				return m_sPropertyVideoStreamingResolution; 
			}
			set { 
				if( value != m_sPropertyVideoStreamingResolution){
					m_sPropertyVideoStreamingResolution = value;
					NotifyPropertyChanged("sPropertyVideoStreamingResolution");
				}
			}  
		}
	


		private const string s_sPropertyVideoStreamingFrameRate = @"Frame rate, fps";
		private string m_sPropertyVideoStreamingFrameRate=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyVideoStreamingFrameRate']/@value")]
		public string sPropertyVideoStreamingFrameRate {
			get { 
				if( m_sPropertyVideoStreamingFrameRate == null){
					return s_sPropertyVideoStreamingFrameRate;
				}
				return m_sPropertyVideoStreamingFrameRate; 
			}
			set { 
				if( value != m_sPropertyVideoStreamingFrameRate){
					m_sPropertyVideoStreamingFrameRate = value;
					NotifyPropertyChanged("sPropertyVideoStreamingFrameRate");
				}
			}  
		}
	


		private const string s_sPropertyVideoStreamingEncoder = @"Encoder";
		private string m_sPropertyVideoStreamingEncoder=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyVideoStreamingEncoder']/@value")]
		public string sPropertyVideoStreamingEncoder {
			get { 
				if( m_sPropertyVideoStreamingEncoder == null){
					return s_sPropertyVideoStreamingEncoder;
				}
				return m_sPropertyVideoStreamingEncoder; 
			}
			set { 
				if( value != m_sPropertyVideoStreamingEncoder){
					m_sPropertyVideoStreamingEncoder = value;
					NotifyPropertyChanged("sPropertyVideoStreamingEncoder");
				}
			}  
		}
	


		private const string s_sPropertyVideoStreamingBitrate = @"Target bitrate, kbps";
		private string m_sPropertyVideoStreamingBitrate=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyVideoStreamingBitrate']/@value")]
		public string sPropertyVideoStreamingBitrate {
			get { 
				if( m_sPropertyVideoStreamingBitrate == null){
					return s_sPropertyVideoStreamingBitrate;
				}
				return m_sPropertyVideoStreamingBitrate; 
			}
			set { 
				if( value != m_sPropertyVideoStreamingBitrate){
					m_sPropertyVideoStreamingBitrate = value;
					NotifyPropertyChanged("sPropertyVideoStreamingBitrate");
				}
			}  
		}
	


		private const string s_sPropertyVideoStreamingPrioriy = @"Priority";
		private string m_sPropertyVideoStreamingPrioriy=null;
		[XPath(@"/localized-strings/module[@name='Constants' and @namespace='nvc']/descendant::string[@name='sPropertyVideoStreamingPrioriy']/@value")]
		public string sPropertyVideoStreamingPrioriy {
			get { 
				if( m_sPropertyVideoStreamingPrioriy == null){
					return s_sPropertyVideoStreamingPrioriy;
				}
				return m_sPropertyVideoStreamingPrioriy; 
			}
			set { 
				if( value != m_sPropertyVideoStreamingPrioriy){
					m_sPropertyVideoStreamingPrioriy = value;
					NotifyPropertyChanged("sPropertyVideoStreamingPrioriy");
				}
			}  
		}
	
	}

}
	