using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("dz.mediaplayer.vlc")]
[assembly: AssemblyDescriptionAttribute("Media player implementation assembly based on VLC.")]
[assembly: AssemblyCompanyAttribute("Digital Zone")]
[assembly: AssemblyConfigurationAttribute("net-2.0 release")]
[assembly: AssemblyVersionAttribute("0.3.1.0")]

